//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizaciones()
        {
            this.Productos_Cotizaciones = new HashSet<Productos_Cotizaciones>();
        }
    
        public int ID_Cotizacion { get; set; }
        public string Codigo_Cotizacion { get; set; }
        public System.DateTime Fecha_Cotización { get; set; }
        public decimal Sub_Total { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Cliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_Cotizaciones> Productos_Cotizaciones { get; set; }
    }
}
